# The list of corals affected by this plugin: (Caps not needed)
stay_alive_coral:
    - TUBE_CORAL_BLOCK
    - BRAIN_CORAL_BLOCK
    - BUBBLE_CORAL_BLOCK
    - FIRE_CORAL_BLOCK
    - HORN_CORAL_BLOCK
    - TUBE_CORAL
    - BRAIN_CORAL
    - BUBBLE_CORAL
    - FIRE_CORAL
    - HORN_CORAL
    - TUBE_CORAL_FAN
    - BRAIN_CORAL_FAN
    - BUBBLE_CORAL_FAN
    - FIRE_CORAL_FAN
    - HORN_CORAL_FAN
    - TUBE_CORAL_WALL_FAN
    - BRAIN_CORAL_WALL_FAN
    - BUBBLE_CORAL_WALL_FAN
    - FIRE_CORAL_WALL_FAN
    - HORN_CORAL_WALL_FAN

#If this is only allowed on certain worlds.
World_Whitelist_Enabled: false
#The worlds this is allowed on.
World_Whitelist:
    - world